apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exporter
    version: testing
  name: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter
      version: testing
  template:
    metadata:
      labels:
        app: exporter
        version: testing
    spec:
      containers:
        - command:
            - "/app/exporter"
            - "-c"
            - "/etc/servicejson/config.json"
          image: exporter:0.1.0
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: /healthcheck
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          name: exporter
          ports:
            - containerPort: 8090
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: /healthcheck
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/servicejson
              name: secret-volume
      volumes:
        - name: secret-volume
          secret:
            defaultMode: 420
            secretName: configfile
